// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/**
 * Detects the Supabase URL based on the current hostname.
 * Automatically uses the correct IP when accessing from mobile device on local network.
 */
function getSupabaseUrl(): string {
  // If production URL is set via env, use it (production/staging)
  const envUrl = import.meta.env.VITE_SUPABASE_URL;
  if (envUrl && !envUrl.includes('127.0.0.1') && !envUrl.includes('localhost')) {
    return envUrl;
  }

  // For local development, detect the hostname
  if (typeof window !== 'undefined') {
    const hostname = window.location.hostname;
    const port = 54321;

    // Use 127.0.0.1 for localhost/127.0.0.1
    if (hostname === 'localhost' || hostname === '127.0.0.1') {
      return `http://127.0.0.1:${port}`;
    }

    // For network access (e.g., 192.168.0.12), use the same hostname
    return `http://${hostname}:${port}`;
  }

  // Fallback for SSR or when window is not available
  return envUrl || `http://127.0.0.1:54321`;
}

const SUPABASE_URL = getSupabaseUrl();
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});